name: ğŸ“¦ Update Dependencies

on:
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: âœ¨ Check for updates with taze
        id: taze
        run: |

          echo "TAZE_OUTPUT<<EOF" >> $GITHUB_ENV
          bunx taze -r -i >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: ğŸ¤– Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): ğŸ¤– update dependencies'
          branch: 'chore/update-dependencies'
          delete-branch: true
          title: 'chore(deps): update dependencies'
          body: |
            This PR updates the project dependencies based on the latest versions available.

            ### Taze Output
            ```
            ${{ steps.taze.outputs.TAZE_OUTPUT }}
            ```
          labels: dependencies, automated
